### ISSUE TITLE
ImportError: cannot import name export_embeddings

### ISSUE THREAD

**Issue by tiffanyguo** [cjekel/tindetheus#20]
I'm getting some import errors for line 39. Any clue how to fix?

**Comment by cjekel** [comment]
That's strange. What version of Python are you using? I test on 3.6.

I'll be away from a computer for a couple days.

**Comment by cjekel** [comment]
I'm back near a computer. Latest version fixed some bugs that were preventing tindetheus from working on Python 2.7. I've tested the latest version on Python 2.7 and 3.6.

I'd be willing to help troubleshoot this issue.

Things that would help for troubleshooting:
- What version of Python are you using?
- How did you install tindetheus?
- What operating system are you using?

**Comment by tiffanyguo** [comment]
Hi Charles,

Thanks for helping me troubleshoot. I'm fairly new to coding and Github
overall so I suspect I'm doing something wrong. I'm using Python 2.7.
Installed tindetheus following your instructions through docker, but then
also tried the native way because of the error I was getting. I'm on a Mac
(Mojave 10.14.6).

Also, apologies if I'm slow to respond. I'm currently a student and have
exams coming up so might not be as quick to check email.

Thanks,
Tiffany

**Comment by tiffanyguo** [comment]
Hi Charles,

Hope this message finds you well. I'm still working through the same error
and haven't yet found a solution. Would I be better off uninstall
everything and then starting over?

Thanks,
Tiffany

**Comment by cjekel** [comment]
Hi Tiffany,

I think the easiest way for you to get up an running will be to create a new virtual environment. I'd recommend Anaconda https://www.anaconda.com/distribution/#download-section . Get the Python 3.7 version, and I'll include some instructions for setting up a new environment and getting this up and running!

Thanks,
CJ

**Comment by cjekel** [comment]
Open the Anaconda terminal. We're going to create a new virtual environment named py36. You'll need to open the anaconda prompt, and then activate this environment every time you want to use tindetheus. I'm going to upload a requirements.txt file soon.
```bash
conda create -n py36 python=3.6
conda activate py36
conda install --file requirements.txt
```

From within the py36 environment, we need to install this version of pynder.
```bash
git clone https://github.com/charliewolf/pynder.git
cd pynder
git fetch origin +refs/pull/211/merge
git checkout -qf FETCH_HEAD
python -m pip install .
cd ..
rm -rf pynder
```

Now we can install tindetheus for the py36 environment.
```bash
pip install tindetheus
```

Let me know if this works for you, and feel free to ask any questions.

**Comment by tiffanyguo** [comment]
Great, thanks so much Charles. Successfully installed Anaconda and am now
on the requirements.txt file part. I'm getting an error that says it can't
be found, but you had mentioned you'd be uploading later, so I'll try again
in a couple hours!

(py36) Tiffanys-2:~ tiffanyguo$ conda install --file requirements.txt


CondaFileIOError: 'requirements.txt'. [Errno 2] No such file or directory:
'requirements.txt'

**Comment by cjekel** [comment]
It's this file https://raw.githubusercontent.com/cjekel/tindetheus/master/requirements.txt

Download it and put it in your home directory.

```
wget https://raw.githubusercontent.com/cjekel/tindetheus/master/requirements.txt
```

**Comment by tiffanyguo** [comment]
Thanks Charles! Was able to make it a little farther this time, but am now
getting an error about cv2. Did I miss a step?

(py36) Tiffanys-2:~ tiffanyguo$ tindetheus browse

Traceback (most recent call last):

  File "/opt/anaconda3/envs/py36/bin/tindetheus", line 5, in <module>

    from tindetheus import command_line_run

  File
"/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tindetheus/__init__.py",
line 1, in <module>

    from .tindetheus import *  # noqa F401

  File
"/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tindetheus/tindetheus.py",
line 44, in <module>

    from tindetheus import export_embeddings

  File
"/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tindetheus/export_embeddings.py",
line 88, in <module>

    from tindetheus.facenet_clone.align import detect_face

  File
"/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tindetheus/facenet_clone/align/detect_face.py",
line 34, in <module>

    import cv2

ModuleNotFoundError: No module named 'cv2'

**Comment by cjekel** [comment]
Oops looks like opencv-python is indeed needed. 
You'll need to run this pip command within that conda virtual environment that you created.
```
pip install opencv-python
```

**Comment by tiffanyguo** [comment]
Gotcha, thanks Charles. I'm now getting errors with the config.txt - I had
followed your instructions on Github and created a txt file with my FB
access ID and put in my home directory.

(py36) Tiffanys-2:~ tiffanyguo$ tindetheus browse

config.txt did not parse this line:

 {\rtf1\ansi\ansicpg1252\cocoartf1671\cocoasubrtf600


config.txt did not parse this line:

 {\fonttbl\f0\fswiss\fcharset0 Helvetica;}


config.txt did not parse this line:

 {\colortbl;\red255\green255\blue255;}


config.txt did not parse this line:

 {\*\expandedcolortbl;;}


config.txt did not parse this line:

 \paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0


config.txt did not parse this line:


\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0


config.txt did not parse this line:




Traceback (most recent call last):

  File "/opt/anaconda3/envs/py36/bin/tindetheus", line 8, in <module>

    sys.exit(command_line_run())

  File
"/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tindetheus/tindetheus.py",
line 294, in command_line_run

    raise('ERROR: No facebook token nor XAuth token in config.txt. '

TypeError: exceptions must derive from BaseException

**Comment by cjekel** [comment]
Are you sure you have something like
```
facebook_token = XXXXXXXXXXXX
```
In the file?

Perhaps the text editor you are using is messing up the encoding. I normally just use vim or vi to create the config.txt file.

**Comment by tiffanyguo** [comment]
Charles, thank you so much for your patience. Finally got through. Just
switched to a different application to create the txt file and it's working
now. Look forward to training my first model! Thank you again - really
appreciate all your help. Apologies in advance if I have to reach out again
and bother you with additional questions, but I should be good for the next
week or so :)

Best,
Tiff

**Comment by tiffanyguo** [comment]
Hi Charles, sorry one last question before I leave you alone for a week.
How do I fix the following error?

FileNotFoundError: [Errno 2] No such file or directory: '20170512-110547'

**Comment by cjekel** [comment]
You need to download a pretrained facenet model. [20170512-110547](https://github.com/davidsandberg/facenet#pre-trained-models) is a 128 embedding model, while there are [other](https://github.com/davidsandberg/facenet#pre-trained-models) 512 embedding models which may be slightly better. 

By default you should be able to see the 20170512-110547 folder when you run tindetheus, but you can also specify the model directory within the config.txt like so
```
model_dir = 20170512-110547  # the location of your facenet model directory
```

**Comment by tiffanyguo** [comment]
Gotcha, thanks again Charles.

**Comment by tiffanyguo** [comment]
Hi Charles,

Happy New Year (I think I'm still allowed to say that since we haven't
spoken in 2020)! I've been able to use tindetheus just fine until recently
- thanks again for getting me up and running! When loading it up this
morning, I got the following error (below). What does this "pickle" error
mean? I never experienced this in the past few weeks that I've been using
tindetheus.

Traceback (most recent call last):

  File
"/opt/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/lib/npyio.py",
line 460, in load

    return pickle.load(fid, **pickle_kwargs)

EOFError: Ran out of input


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/anaconda3/envs/py36/bin/tindetheus", line 8, in <module>

    sys.exit(command_line_run())

  File
"/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tindetheus/tindetheus.py",
line 299, in command_line_run

    retries=defaults['retries'])

  File
"/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tindetheus/tindetheus.py",
line 148, in main

    tfsess=sess, x_auth_token=x_auth_token)

  File
"/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tindetheus/tinder_client.py",
line 118, in __init__

    allow_pickle=True))

  File
"/opt/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/lib/npyio.py",
line 463, in load

    "Failed to interpret file %s as a pickle" % repr(file))

OSError: Failed to interpret file 'al_database.npy' as a pickle

**Comment by cjekel** [comment]
I'm glad the program has been working for you.

If you are not so interested in the _auto like database_, you can simply just rename ```al_database.npy``` to something like ```al_database_old.npy```. This will mess up your auto like count, but I'm not sure it's a big deal.

Did you happen to upgrade your numpy library? I'm not sure why this happened in the first place.

**Comment by tiffanyguo** [comment]
Hi Charles,

Thanks for that tip! Renaming the al_database.npy file did the trick! I
didn't upgrade my numpy library so I'm also confused as to how this
happened. It was working fine and then one day, I got this error. Anyway,
it seems to be working again. Appreciate all your help thus far - you've
been so kind.

Best,
Tiffany
